### ISSUE TITLE
Bug: using -wgn crashes commander

### ISSUE THREAD

**Issue by benjaminbollen** [mosaicdao/mosaic-chains#109]
bug when using `-wgn` option, `commander` crashes.

```
aboki5:mosaic-chains ben$ ./mosaic start 1414 -wgn
error: could not convert input to integer {"service":"mosaic-chains","input":"-g","timestamp":"2019-07-02T08:11:16.235Z"}
error: uncaughtException: could not convert input to integer
Error: could not convert input to integer
    at Integer.parseString (/Users/ben/openst/mosaic-chains/src/Integer.ts:14:13)
    at Command.<anonymous> (/Users/ben/openst/mosaic-chains/node_modules/commander/index.js:412:13)
    at Command.emit (events.js:189:13)
    at Command.parseOptions (/Users/ben/openst/mosaic-chains/node_modules/commander/index.js:733:14)
    at Command.parse (/Users/ben/openst/mosaic-chains/node_modules/commander/index.js:471:21)
    at Object.<anonymous> (/Users/ben/openst/mosaic-chains/src/bin/mosaic-start.ts:63:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (/Users/ben/openst/mosaic-chains/node_modules/ts-node/src/index.ts:414:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/ben/openst/mosaic-chains/node_modules/ts-node/src/index.ts:417:12) {"error":{},"stack":"Error: could not convert input to integer\n    at Integer.parseString (/Users/ben/openst/mosaic-chains/src/Integer.ts:14:13)\n    at Command.<anonymous> (/Users/ben/openst/mosaic-chains/node_modules/commander/index.js:412:13)\n    at Command.emit (events.js:189:13)\n    at Command.parseOptions (/Users/ben/openst/mosaic-chains/node_modules/commander/index.js:733:14)\n    at Command.parse (/Users/ben/openst/mosaic-chains/node_modules/commander/index.js:471:21)\n    at Object.<anonymous> (/Users/ben/openst/mosaic-chains/src/bin/mosaic-start.ts:63:4)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Module.m._compile (/Users/ben/openst/mosaic-chains/node_modules/ts-node/src/index.ts:414:23)\n    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Object.require.extensions.(anonymous function) [as .ts] (/Users/ben/openst/mosaic-chains/node_modules/ts-node/src/index.ts:417:12)","exception":true,"date":"Tue Jul 02 2019 13:41:16 GMT+0530 (India Standard Time)","process":{"pid":12291,"uid":501,"gid":20,"cwd":"/Users/ben/openst/mosaic-chains","execPath":"/Users/ben/.nvm/versions/node/v10.15.3/bin/node","version":"v10.15.3","argv":["/Users/ben/.nvm/versions/node/v10.15.3/bin/node","/Users/ben/openst/mosaic-chains/src/bin/mosaic-start.ts","1414","-w","-g","-n"],"memoryUsage":{"rss":191799296,"heapTotal":162451456,"heapUsed":131825736,"external":161338}},"os":{"loadavg":[2.54052734375,2.2138671875,2.23974609375],"uptime":167057},"trace":[{"column":13,"file":"/Users/ben/openst/mosaic-chains/src/Integer.ts","function":"Integer.parseString","line":14,"method":"parseString","native":false},{"column":13,"file":"/Users/ben/openst/mosaic-chains/node_modules/commander/index.js","function":null,"line":412,"method":null,"native":false},{"column":13,"file":"events.js","function":"Command.emit","line":189,"method":"emit","native":false},{"column":14,"file":"/Users/ben/openst/mosaic-chains/node_modules/commander/index.js","function":"Command.parseOptions","line":733,"method":"parseOptions","native":false},{"column":21,"file":"/Users/ben/openst/mosaic-chains/node_modules/commander/index.js","function":"Command.parse","line":471,"method":"parse","native":false},{"column":4,"file":"/Users/ben/openst/mosaic-chains/src/bin/mosaic-start.ts","function":null,"line":63,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":701,"method":"_compile","native":false},{"column":23,"file":"/Users/ben/openst/mosaic-chains/node_modules/ts-node/src/index.ts","function":"Module.m._compile","line":414,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":712,"method":".js","native":false},{"column":12,"file":"/Users/ben/openst/mosaic-chains/node_modules/ts-node/src/index.ts","function":"Object.require.extensions.(anonymous function) [as .ts]","line":417,"method":"ts]","native":false}],"service":"mosaic-chains","timestamp":"2019-07-02T08:11:16.263Z"}
```

**Comment by deepesh-kn** [comment]
This is resolved, use -g option.
